---
title: Site worflow
author: arnabold
---

References:
  + [[https://www.stackbuilders.com/news/dr-hakyll-create-a-github-page-with-hakyll-and-circleci][DR. HAKYLL: CREATE A GITHUB PAGE WITH HAKYLL AND CIRCLECI]]
  + [[https://jaspervdj.be/hakyll/tutorials/01-installation.html][Installation]]

* Configure Git and GitHub

A github repository named [[https://arnabold.github.io/][arnabold.github.io]] . The =master= branch is
used by github to publish your site. The idea is to have a =continuous
integration service= to do that for you.

Create an =orphan= branch named =hakyll= for the source of your
site. The =hakyll= branch will contain your site configuration and content.

#+BEGIN_SRC shell

  $ git checkout --orphan hakyll
  # Switched to a new branch 'hakyll'

#+END_SRC

Add your github repository as a git =submodule= at =_site=

#+BEGIN_SRC shell

  $ git submodule add git@github.com:arnabold/arnabold.github.io.git _site
  # Adding existing repo at '_site' to the index

  $ git commit -m "Create hakyll branch"
  # [hakyll (root-commit) 875635c] Create hakyll branch
  # ...

  $ git push -u origin hakyll
  # To https://github.com/arnabold/arnabold.github.io.git
  # * [new branch]      hakyll -> hakyll
  # Branch hakyll set up to track remote branch hakyll from origin.

#+END_SRC

Hakyll generates your site in a directory called =_site=, you can use
that directory to update the site published by GitHub.

* Configure Hakyll

** Hakyll installation

#+BEGIN_SRC shell

  $ stack install hakyll
  # for a specific version try stack install hakyll-4.9.0.0

#+END_SRC

** Site development

*** Haskell project initialization and build

#+BEGIN_SRC shell

  $ cd arnabold.github.io

  $ hakyll-init .
  # create an haskell project with some templates

  $ stack init
  # configure the haskell project to be used with stack
  # for example setup the resolver for this project
  # Selected resolver: nightly-2016-11-13

  $ stack build
  
#+END_SRC

*** Hakyll project build 

#+BEGIN_SRC shell

  $ stack exec site build
  # build the site
  # use it when you just made changes to the contents of your website

  $ stack exec site clean
  # clean the site and removes the generated directories site and cache

  $ stack exec site rebuild
  # clean and build
  # If you made changes to site.hs, you need to recompile it followed by a rebuild

#+END_SRC

Project layout:
  - =_site= contains your site as HTML files, ready to be deployed
  - =_cache= is used internally by Hakyll 

*** Hakyll project run

#+BEGIN_SRC shell

  $ stack exec site watch
  # Listening on http://127.0.0.1:8000
  # Ctrl-C to kill the server 

#+END_SRC


** Git ignore configuration
Take =.gitignore= from [[https://github.com/github/gitignore/blob/master/Haskell.gitignore][Haskell ignored files]] and add =_site= and
=_cache= and =*~=

** Commit and push

#+BEGIN_SRC shell

  $ git add --all
  $ git commit -m "Configure Hakyll"

#+END_SRC

While waiting until =CircleCI= is configured 

#+BEGIN_SRC shell

  $ git push origin hakyll

#+END_SRC
