---
title: Publishing Workflow
author: arnabold
---

References:
  + [[https://jaspervdj.be/hakyll/tutorials/01-installation.html][Installation]]
  + [[https://www.stackbuilders.com/news/dr-hakyll-create-a-github-page-with-hakyll-and-circleci][DR. HAKYLL: CREATE A GITHUB PAGE WITH HAKYLL AND CIRCLECI]]


* Configure Git and GitHub

GitHub uses the =master= branch to publish a /user site/

  + From [[https://github.com][github.com]] create a repository named =<username>.github.io=
    (i.e.: [[https://arnabold.github.io/][arnabold.github.io]])

  + Initialize the local git repository, then commit and push an empty master
    branch

    #+BEGIN_SRC shell
    $ mkdir arnabold.github.io
    $ cd arnabold.github.io
    $ git init
    $ git commit --allow-empty -m "Create master branch"
    $ git remote add origin git@github.com:arnabold/arnabold.github.io.git
    $ git push -u origin master
    #+END_SRC
 
  + Create and switch to an =orphan= branch named =hakyll=. The =hakyll= branch will
    contain the configuration and content of your site: 
    
    ~$ git checkout --orphan hakyll~.

  + Add, commit and push the repository as a [[https://git-scm.com/book/en/v2/Git-Tools-Submodules][git submodule]] at =_site= folder

    #+BEGIN_SRC shell
    $ git submodule add git@github.com:arnabold/arnabold.github.io.git _site
    $ git commit -m "Create hakyll branch"
    $ git push -u origin hakyll
    #+END_SRC

    Hakyll generates the site in a directory called =_site=, you can
    use that directory to update the site published by GitHub.

  + Git ignore configuration. Download =.gitignore= from [[https://github.com/github/gitignore/blob/master/Haskell.gitignore][Haskell
    ignored files]] and add =_site/=, =_cache/= and =*~=.

* Configure Hakyll project with stack

+ Install hakyll.

  ~$ stack install hakyll~

  or for a specific version

  ~$ stack install hakyll-4.9.0.0~
  
+ Hakyll project initialization.

  #+BEGIN_SRC shell
  $ cd arnabold.github.io
  $ hakyll-init .
  $ stack init
  $ stack build
  #+END_SRC

  Project layout:
  - =_site= contains your site as HTML files, ready to be deployed
  - =_cache= is used internally by Hakyll 

+ Hakyll project build. Use it when you just made changes to the
  contents of your website. It affects the generation of =_site= and
  =_cache= folders

  #+BEGIN_SRC shell
  $ stack exec site build
  $ stack exec site clean
  $ stack exec site rebuild
  #+END_SRC

  If you made changes to =site.hs=, you need to recompile it followed
  by a rebuild

  #+BEGIN_SRC shell
  $ stack build
  $ stack exec site rebuild
  #+END_SRC

+ Hakyll project run.

  ~$ stack exec site watch~

  Hakyll is listening on =http://127.0.0.1:8000=. Use =Ctrl-C= to kill the server.

+ Hakyll project commit and push

  #+BEGIN_SRC shell
  $ git add --all
  $ git commit -m "Configure Hakyll"
  $ git push origin hakyll
  #+END_SRC

* Publishing worflow

** TODO The idea is to have a =continuous integration service= like =CircleCI= to automate the publishing workflow.

** Manual workflow

After commiting all the staged changes, (while in the hakyll branch)

+ Uupdate the /stack package index/

  ~$ stack update~ 

+ Build the hakyll project 

  ~$ stack build~

+ Initilize and update the submodule recorded in the index

  #+BEGIN_SRC shell
  $ git submodule init
  $ git submodule update
  #+END_SRC

+ Generate the site, after updating the =_site= folder  in the working
  tree

  #+BEGIN_SRC shell
  $ (cd _site && git checkout master)
  $ stack exec site build
  #+END_SRC

+ Commit and push all changes in =_site= to =master= branch using the
  current date and time as reference in the commit message.

  #+BEGIN_SRC 
  $ (cd _site && git status)
  $ (cd _site && git add --all)
  $ (cd _site && git commit -m "Update (`date '+%F %T %Z'`)")
  $ (cd _site && git push origin master)
  #+END_SRC

+ Update the submodule in the hakyll branch. Hakyll branch has a
  static reference to a commit in the master branch. hakyll branch
  must be  update to to point to the latest commit.
  
  #+BEGIN_SRC 
  $ git status
  $ git add _site
  $ git commit -m "Update _site (`date '+%F %T %Z'`)"
  $ git push origin hakyll
  #+END_SRC









